[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:core]
command=python3 core/launcher.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED=1
