# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/serving/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core/serving/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ore/serving/inference.proto\"9\n\x11PredictionRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\"c\n\x12PredictionResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nprediction\x18\x02 \x01(\x02\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"R\n\x16\x42\x61tchPredictionRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12$\n\x08requests\x18\x02 \x03(\x0b\x32\x12.PredictionRequest\"k\n\x17\x42\x61tchPredictionResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0bpredictions\x18\x02 \x03(\x02\x12\x13\n\x0b\x63onfidences\x18\x03 \x03(\x02\x12\x12\n\ntimestamps\x18\x04 \x03(\x03\x32\x8d\x01\n\x10InferenceService\x12\x34\n\x07Predict\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x12\x43\n\x0c\x42\x61tchPredict\x12\x17.BatchPredictionRequest\x1a\x18.BatchPredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.serving.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=32
  _globals['_PREDICTIONREQUEST']._serialized_end=89
  _globals['_PREDICTIONRESPONSE']._serialized_start=91
  _globals['_PREDICTIONRESPONSE']._serialized_end=190
  _globals['_BATCHPREDICTIONREQUEST']._serialized_start=192
  _globals['_BATCHPREDICTIONREQUEST']._serialized_end=274
  _globals['_BATCHPREDICTIONRESPONSE']._serialized_start=276
  _globals['_BATCHPREDICTIONRESPONSE']._serialized_end=383
  _globals['_INFERENCESERVICE']._serialized_start=386
  _globals['_INFERENCESERVICE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
