#!/usr/bin/env python3
"""
MARK5 CROSS-SECTIONAL RANKING ENGINE 
Fix: Aligning perfectly with test.py's signal generator to prevent noise trading.
"""

import os
import sys
import logging
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Ensure MARK5 root is in path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.utils.common import setup_logger
from scripts.test import MARK5ValidationEngine, download_data
from core.trading.position_sizer import VolatilityAwarePositionSizer

logger = setup_logger("MARK5.CrossSectional", level=logging.INFO, log_file="logs/cross_sectional.log")

# Configuration (Aggressive but Smart)
MAX_HOLD_BARS = 15              # Matches Triple-Barrier time limit
PORTFOLIO_CAPITAL = 50000000.0  # 5 Crore INR starting capital (Institutional scale)
COST_PTS = 0.0015               # 0.15% round trip expected cost (Realistic Indian Market Cost)
MAX_POSITION_ABS = 2500000.0      # Max Rs 25L per position ABS limit (Fixed from 50k contradiction)
TOP_N_LONG = 5                  # Rank top 5
COOLDOWN_BARS = 3               # Bars to wait after a stock exits before re-entering (Matches test.py)

def extract_daily_predictions(symbol, data, engine):
    """Run the engine's paper walk to harvest the EXACT signals generated by predictor.py."""
    try:
        df_predictions = engine.generate_predictions(symbol, data)
        if df_predictions.empty:
            return pd.DataFrame()
            
        test_results = df_predictions[df_predictions['dataset_type'] == 'Test'].copy()
        if test_results.empty:
            return pd.DataFrame()
            
        test_results = test_results.reset_index()
        if 'index' in test_results.columns and 'timestamp' not in test_results.columns:
             test_results.rename(columns={'index': 'timestamp'}, inplace=True)
             
        test_results['symbol'] = symbol
        
        # WE MUST INGEST predicted_signal to know if the model ACTUALLY issued a BUY!
        if 'predicted_signal' not in test_results.columns:
            logger.error(f"Missing predicted_signal in test_results for {symbol}!")
            return pd.DataFrame()
            
        # Compute ATR for Position Sizer
        data['atr_14'] = (data['high'] - data['low']).rolling(14).mean().bfill()
        test_results = test_results.merge(data[['atr_14']], left_on='timestamp', right_index=True, how='left')
        
        return test_results[['timestamp', 'predicted_probability', 'confidence', 'symbol', 'close', 'predicted_signal', 'atr_14']]
    except Exception as e:
        logger.error(f"Failed extracting predictions for {symbol}: {e}")
        return pd.DataFrame()

def simulate_cross_sectional_portfolio(all_preds: pd.DataFrame):
    """Simulate a portfolio using ONLY valid signals generated by the base pipeline."""
    logger.info("Starting Precision Cross-Sectional Portfolio Simulation...")
    
    dates = sorted(all_preds['timestamp'].unique())
    capital = PORTFOLIO_CAPITAL
    peak_equity = PORTFOLIO_CAPITAL
    
    # Initialize V2 Alpha Position Sizer
    position_sizer = VolatilityAwarePositionSizer(
        initial_capital=PORTFOLIO_CAPITAL,
        default_risk_per_trade=0.015,   # 1.5% Risk per trade
        max_position_size_pct=0.05,     # 5% Max position size
        atr_stop_multiplier=2.0,        # 2x ATR Stop
        max_concurrent_positions=20     # Nifty 50 allows 20 concurrent trades
    )
    
    positions = []
    portfolio_history = []
    cooldowns = {} # {symbol: cooldown_remaining}
    closed_trades = [] # To track EV validation
    
    for i, current_date in enumerate(dates):
        daily_data = all_preds[all_preds['timestamp'] == current_date].copy()
        
        # 0. Decrement Cooldowns
        for sym in list(cooldowns.keys()):
            if cooldowns[sym] > 0:
                cooldowns[sym] -= 1
        
        # 1. Update existing positions & Check Exits
        current_equity = capital
        for pos in positions:
            sym_data = daily_data[daily_data['symbol'] == pos['symbol']]
            if not sym_data.empty:
                current_price = sym_data.iloc[0]['close']
                if not pos.get('is_short', False):
                    # Long: Asset value is qty * current_price
                    current_equity += pos['qty'] * current_price
                else:
                    # Short: Liability is qty * current_price, but we hold cash from selling.
                    # Net equity = Cash (capital) + (Entry Value - Current Liability)
                    # We compute the unrealized PnL: (pos['entry_price'] - current_price) * qty
                    unrealized_pnl = (pos['entry_price'] - current_price) * pos['qty']
                    current_equity += (pos['entry_price'] * pos['qty']) + unrealized_pnl
            else:
                # If no data today, use entry capital locked
                if not pos.get('is_short', False):
                    current_equity += pos['qty'] * pos['entry_price']
                else:
                    current_equity += pos['qty'] * pos['entry_price']
                
        # Update Peak Equity
        if current_equity > peak_equity:
             peak_equity = current_equity
             
        # Circuit Breaker: -10% Peak Drawdown Hard Stop
        allow_entries = True
        if (current_equity - peak_equity) / peak_equity < -0.10:
            allow_entries = False
            
        exits_today = []
        for pos in positions:
            sym_data = daily_data[daily_data['symbol'] == pos['symbol']]
            if sym_data.empty:
                pos['bars_held'] += 1
                continue
                
            current_price = sym_data.iloc[0]['close']
            pos['bars_held'] += 1
            
            should_exit = False
            
            should_exit = False
            
            # v5.0 Triple-Barrier & Trailing Chandelier Exit Simulation
            # Update peak/trough for trailing stops
            if current_price > pos.get('highest_high', pos['entry_price']):
                pos['highest_high'] = current_price
            if current_price < pos.get('lowest_low', pos['entry_price']):
                pos['lowest_low'] = current_price
                
            atr = pos.get('atr_at_entry', current_price * 0.02)
            is_short = pos.get('is_short', False)
            
            if not is_short:
                # LONG Logic
                pt_price = pos['entry_price'] + (atr * 2.0)
                sl_price = pos['entry_price'] - (atr * 1.0)
                # Trailing Stop: 1.5 ATR from highest high
                trailing_stop = pos['highest_high'] - (atr * 1.5)
                # Hard stop ratchets up
                sl_price = max(sl_price, trailing_stop)
                
                if current_price >= pt_price:
                    should_exit = True
                    exit_reason = "PROFIT_TARGET"
                elif current_price <= sl_price:
                    should_exit = True
                    exit_reason = "TRAILING_STOP" if trailing_stop >= sl_price else "STOP_LOSS"
                elif pos['bars_held'] >= MAX_HOLD_BARS:
                    should_exit = True
                    exit_reason = "TIME_LIMIT"
                    
                loss_pct = (pos['entry_price'] - current_price) / pos['entry_price']
                
            else:
                # SHORT Logic
                pt_price = pos['entry_price'] - (atr * 2.0)
                sl_price = pos['entry_price'] + (atr * 1.0)
                trailing_stop = pos['lowest_low'] + (atr * 1.5)
                sl_price = min(sl_price, trailing_stop)
                
                if current_price <= pt_price:
                    should_exit = True
                    exit_reason = "PROFIT_TARGET"
                elif current_price >= sl_price:
                    should_exit = True
                    exit_reason = "TRAILING_STOP" if trailing_stop <= sl_price else "STOP_LOSS"
                elif pos['bars_held'] >= MAX_HOLD_BARS:
                    should_exit = True
                    exit_reason = "TIME_LIMIT"
                    
                loss_pct = (current_price - pos['entry_price']) / pos['entry_price']
                
            # Emergency Stop (-5% Hard crash protector)
            if loss_pct > 0.05:
                 should_exit = True
                 exit_reason = "EMERGENCY_STOP"
                 
            if should_exit:
                val = pos['qty'] * current_price
                cost = val * (COST_PTS / 2) # Exit cost
                
                if not is_short:
                    net_pnl = (val - cost) - (pos['qty'] * pos['entry_price'] + pos['entry_cost'])
                    capital += (val - cost)
                    ret_pct = (current_price / pos['entry_price']) - 1
                else:
                    # Short PNL logic (you sell high initially, buy low to cover)
                    entry_val = pos['qty'] * pos['entry_price']
                    net_pnl = (entry_val - pos['entry_cost']) - (val + cost)
                    capital += (entry_val - val - cost)  # Return capital + profit
                    ret_pct = (pos['entry_price'] / current_price) - 1
                
                closed_trades.append({
                    'symbol': pos['symbol'],
                    'entry_price': pos['entry_price'],
                    'exit_price': current_price,
                    'bars_held': pos['bars_held'],
                    'predicted_prob': pos['predicted_prob'],
                    'confidence': pos['confidence'],
                    'is_short': is_short,
                    'exit_reason': exit_reason,
                    'net_pnl': net_pnl,
                    'return_pct': ret_pct
                })
                
                # Feedback to Position Sizer
                position_sizer.record_trade_result(net_pnl)
                position_sizer.close_position(pos['symbol'])
                
                exits_today.append(pos)
                cooldowns[pos['symbol']] = COOLDOWN_BARS
                
        for p in exits_today:
            positions.remove(p)
            
        # Re-calc equity after exits
        current_equity = capital
        for pos in positions:
            sym_data = daily_data[daily_data['symbol'] == pos['symbol']]
            if not sym_data.empty:
                current_price = sym_data.iloc[0]['close']
                if not pos.get('is_short', False):
                    current_equity += pos['qty'] * current_price
                else:
                    unrealized_pnl = (pos['entry_price'] - current_price) * pos['qty']
                    current_equity += (pos['entry_price'] * pos['qty']) + unrealized_pnl
            else:
                current_equity += pos['qty'] * pos['entry_price']
                
        # Update Position Sizer Capital
        position_sizer.update_capital(current_equity)
                
        # 2. Rank & Enter New Positions (ONLY for VALIDATED BUY SIGNALS)
        if allow_entries and len(positions) < TOP_N_LONG:
            room = TOP_N_LONG - len(positions)
            
            candidates = daily_data[~daily_data['symbol'].isin([p['symbol'] for p in positions])].copy()
            
            # THE FIX: Deploy capital if predictor.py explicitly flagged it as a BUY (1) or SHORT (-1)
            # AND the symbol is not in cooldown
            candidates = candidates[candidates['predicted_signal'].isin([1, -1])]
            candidates = candidates[~candidates['symbol'].isin([s for s, c in cooldowns.items() if c > 0])]
            
            # Rank the remaining valid signals by predicted edge
            if not candidates.empty:
                candidates['score'] = candidates['predicted_probability'] * candidates['confidence']
                top_candidates = candidates.sort_values(by='score', ascending=False).head(room)
                
                for _, row in top_candidates.iterrows():
                    # 99% Max Invested capability
                    if capital < current_equity * 0.01:
                        break
                        
                    close_price = row['close']
                    atr = row['atr_14']
                    
                    if pd.isna(atr) or atr <= 0:
                        atr = close_price * 0.02 # Fallback to 2% volatility
                    
                    # --- V2 ALPHA: PRO SIZING ---
                    # Use VolatilityAwarePositionSizer instead of naive allocation
                    qty, size_details = position_sizer.calculate_size(
                        symbol=row['symbol'],
                        price=close_price,
                        atr=atr,
                        conviction=row['confidence']
                    )
                    
                    if qty <= 0:
                        continue # Sizer vetoed the trade (e.g., too risky or capped)
                        
                    val = qty * close_price
                    if val > capital:
                        qty = int(capital / close_price)
                        val = qty * close_price
                        
                    if qty > 0:
                        cost = val * (COST_PTS / 2) # Entry cost
                        
                        if not row['predicted_signal'] == -1:
                            capital -= (val + cost) # Long consumes capital
                        else:
                            capital -= cost # Short consumes margin/collateral + cost. (To simplify, we deduct exactly entry cost, and track liability)
                            capital -= val # We also lock the margin requirement (100% margin for simple cash sim)
                        # Check if it was a SHORT signal (-1) or LONG (1)
                        is_short = row['predicted_signal'] == -1
                        
                        position_sizer.register_position(row['symbol'], val)
                        
                        positions.append({
                            'symbol': row['symbol'],
                            'qty': qty,
                            'entry_price': close_price,
                            'entry_cost': cost,
                            'bars_held': 0,
                            'entry_date': current_date,
                            'predicted_prob': row['predicted_probability'],
                            'confidence': row['confidence'],
                            'is_short': is_short,
                            'highest_high': close_price, # Track for Trailing Stop
                            'lowest_low': close_price,
                            'atr_at_entry': atr
                        })

        portfolio_history.append({
            'timestamp': current_date,
            'capital': capital,
            'equity': current_equity,
            'active_positions': len(positions)
        })

    df_port = pd.DataFrame(portfolio_history)
    df_port.set_index('timestamp', inplace=True)
    
    # Analyze closed trades for EV Validation
    if closed_trades:
        df_trades = pd.DataFrame(closed_trades)
        pt_hits = len(df_trades[df_trades['exit_reason'] == 'PROFIT_TARGET'])
        hit_rate = pt_hits / len(df_trades)
        logger.info("=========================================")
        logger.info(f"META-LABELING EV VALIDATION ({len(df_trades)} Trades)")
        logger.info("=========================================")
        logger.info(f"Target Hit Rate: {hit_rate:.2%}")
        logger.info(f"Avg Predicted Prob: {df_trades['predicted_prob'].mean():.2%}")
        logger.info(f"Avg Realized Return: {df_trades['return_pct'].mean():.2%}")
        
        if hit_rate < 0.40:
            logger.warning("🚨 REALIZED HIT RATE < 40%. BASE EDGE IS TOO WEAK.")
        else:
            logger.info("✅ EV HURDLE CLEARED.")
            
        df_trades.to_csv('reports/cross_sectional/ev_validation.csv', index=False)
        
    return df_port

def generate_tearsheet(df_port):
    """Generate professional tearsheet for the portfolio."""
    os.makedirs('reports/cross_sectional', exist_ok=True)
    
    df_port['daily_return'] = df_port['equity'].pct_change().fillna(0)
    
    metrics = {}
    metrics['total_return'] = (df_port['equity'].iloc[-1] / df_port['equity'].iloc[0]) - 1
    
    daily_rf = 0.0 # Strict active
    excess_ret = df_port['daily_return'].mean() - daily_rf
    if df_port['daily_return'].std() > 0:
        metrics['sharpe_ratio'] = (excess_ret / df_port['daily_return'].std()) * np.sqrt(252)
    else:
        metrics['sharpe_ratio'] = 0.0
        
    roll_max = df_port['equity'].cummax()
    drawdown = df_port['equity'] / roll_max - 1.0
    metrics['max_drawdown'] = drawdown.min()
    
    plt.style.use('dark_background')
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), gridspec_kw={'height_ratios': [3, 1]})
    
    ax1.plot(df_port.index, df_port['equity'], color='#00ff00', linewidth=2)
    ax1.set_title(f'MARK5 Alpha Portfolio (Return: {metrics["total_return"]:.2%}, Sharpe: {metrics["sharpe_ratio"]:.2f})', fontweight='bold')
    ax1.set_ylabel('Portfolio Value (INR)')
    ax1.grid(color='#333333', linestyle='--')
    
    ax2.plot(df_port.index, drawdown * 100, color='#ff0000', linewidth=1)
    ax2.fill_between(df_port.index, drawdown * 100, 0, color='#ff0000', alpha=0.3)
    ax2.set_title(f'Drawdown (Max: {metrics["max_drawdown"]:.2%})')
    ax2.set_ylabel('Drawdown %')
    ax2.grid(color='#333333', linestyle='--')
    
    plt.tight_layout()
    plt.savefig('reports/cross_sectional/portfolio_tearsheet.png', dpi=300)
    plt.close()
    
    logger.info("=================================")
    logger.info("🔥 ALPHA METRICS ACHIEVED 🔥")
    logger.info("=================================")
    logger.info(f"Total Return: {metrics['total_return']:.2%}")
    logger.info(f"Sharpe Ratio: {metrics['sharpe_ratio']:.2f}")
    logger.info(f"Max Drawdown: {metrics['max_drawdown']:.2%}")
    logger.info("=================================")

def main():
    try:
        from scripts.nifty50_universe import NIFTY_50_TICKERS
        tickers = NIFTY_50_TICKERS
    except ImportError:
        tickers = ['RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS', 'SBIN.NS', 'AARTIIND.NS', 'ITC.NS', 'LT.NS', 'BAJFINANCE.NS', 'HINDUNILVR.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS', 'ATGL.NS', 'WIPRO.NS']
         
    fast_tickers = tickers
    logger.info(f"Initializing Precision Cross-Sectional Analysis for {len(fast_tickers)} stocks...")
    
    data = download_data(fast_tickers)
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--optimize', action='store_true', help='Trigger Optuna Bayesian Optimization')
    args, _ = parser.parse_known_args()
    
    engine = MARK5ValidationEngine(optimize=args.optimize)
    
    all_preds_list = []
    
    for i, symbol in enumerate(fast_tickers, 1):
        if symbol in data:
            logger.info(f"[{i}/{len(fast_tickers)}] Extracting signals for {symbol}")
            preds = extract_daily_predictions(symbol, data[symbol], engine)
            if not preds.empty:
                 num_buys = len(preds[preds['predicted_signal'] == 1])
                 if num_buys > 0:
                     logger.info(f"[{symbol}] Found {num_buys} BUY signals.")
                     all_preds_list.append(preds)
                 
    if not all_preds_list:
        logger.error("No predictions generated.")
        return
        
    combined_predictions = pd.concat(all_preds_list, ignore_index=True)
    logger.info(f"Aggregated {len(combined_predictions)} daily predictions across universe.")
    
    portfolio = simulate_cross_sectional_portfolio(combined_predictions)
    generate_tearsheet(portfolio)

if __name__ == "__main__":
    main()
